name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn
    - name: Lint
      run: yarn run lint
    - name: Unit Tests
      run: yarn run test
    - name: E2E Tests
      run: yarn run e2e
